-- Seed Academy Journal articles migrated from digica-academy-lms.
-- Run in Supabase SQL Editor or via: supabase db push

INSERT INTO public.lms_articles (
  id,
  slug,
  category,
  title,
  excerpt,
  body_html,
  status,
  published_at,
  display_date,
  read_time_minutes,
  read_time_display
)
VALUES
(
  gen_random_uuid(),
  'write-the-metric-definition-before-the-dashboard',
  'Analytics',
  'Write the Metric Definition Before You Build the Dashboard',
  'Teams argue about “revenue” because nobody agreed on grain, filters, and ownership first. Definition first — charts second.',
  '<p>Dashboards get built fast when someone asks for “a revenue view.” Then finance, product, and growth each mean something different — gross vs net, booked vs paid, with or without refunds — and the meeting dissolves into who owns the number.</p><p>A metric definition is a short contract: name, business question, grain (order? customer? day?), inclusions and exclusions, time zone, and who can change it. Write that before you open a charting tool. The doc is boring on purpose; it prevents expensive surprise later.</p><p>Digica’s Mini Bootcamp Data Analytics treats this as part of the loop: clarify the question, lock the definition, then clean and visualize. Mentors push on “what exactly are we counting?” until your slide would survive a product standup.</p><p>Portfolio tip: include a one-paragraph metric spec next to your chart. Hiring managers notice when you can defend the number, not only decorate it.</p><p>Pretty visuals without shared definitions create false confidence. Analysts who start with the contract earn trust when the dashboard number moves.</p>',
  'published',
  '2026-08-25T17:00:00.000Z'::timestamptz,
  'August 26, 2026',
  5,
  '5 min read'
),
(
  gen_random_uuid(),
  'pick-the-metric-that-matches-the-cost-of-being-wrong',
  'Data Science',
  'Pick the Metric That Matches the Cost of Being Wrong',
  'Accuracy looks great in a notebook. Interviews and production ask whether you optimized for the mistake that actually hurts.',
  '<p>Defaulting to accuracy is easy — and often wrong. On imbalanced labels, a model that always predicts the majority class looks “good” while missing every rare event that matters. The real question is which error costs more: a false positive or a false negative.</p><p>Map the business cost before you tune. Fraud, churn, and medical triage rarely share the same tradeoff. Precision, recall, F1, or a simple cost-weighted score should follow that map — not a leaderboard habit.</p><p>Digica’s Data Science Bootcamp asks for that defense in capstones: which metric, why, and what happens when the model is wrong. Mentors treat metric choice as a product decision, not a library default.</p><p>In interviews, lead with the cost story, then the number. “We optimized recall because missing a churner was expensive” beats “we got 94% accuracy” every time.</p><p>A slightly weaker model on the right metric beats a perfect score on the wrong one. Clarity about tradeoffs is part of the deliverable.</p>',
  'published',
  '2026-08-18T17:00:00.000Z'::timestamptz,
  'August 19, 2026',
  6,
  '6 min read'
),
(
  gen_random_uuid(),
  'when-your-resume-still-says-something-else',
  'Career',
  'When Your Resume Still Says Something Else',
  'Career switchers do not need a fake title — they need a consistent story: transferable judgment, sharp projects, and a clear target role.',
  '<p>Your last job title may still say ops, sales, or finance while your nights are full of SQL and notebooks. Hiding that gap looks evasive. Owning the transition — with proof — looks intentional.</p><p>Lead with outcomes that transfer: decisions you informed, messy data you cleaned, stakeholders you briefed. Put one or two portfolio projects above the fold so the target role is obvious before someone scrolls to employment history.</p><p>Digica live bootcamps exist partly for this narrative: mentor feedback, cohort deadlines, and deliverables you can defend out loud. That is easier to explain than “I watched tutorials alone.”</p><p>Align LinkedIn, CV, and interview stories to one role title (analyst vs scientist). Mixed signals make recruiters guess — and guessing rarely favors the switcher.</p><p>You do not need to invent experience. You need a coherent path from where you were to the work you can already show.</p>',
  'published',
  '2026-08-14T17:00:00.000Z'::timestamptz,
  'August 15, 2026',
  5,
  '5 min read'
),
(
  gen_random_uuid(),
  'sql-window-functions-that-interviewers-love',
  'SQL',
  'Window Functions That Actually Show Up in Interviews',
  'RANK, LAG, and running totals — not as trivia, but as the moves analysts use when stakeholders ask “compared to last month?”',
  '<p>Most beginners stop at GROUP BY. That is enough for a weekly report — until a hiring manager asks how revenue changed week over week without collapsing every row into one number. That is where window functions earn their keep.</p><p>Think of a window as “look at this row, but also see its neighbors.” LAG compares to the previous period. SUM() OVER (ORDER BY …) builds a running total. RANK surfaces top performers without filtering the rest of the table away.</p><p>In Digica’s Mini Bootcamp SQL, we treat window functions as a project skill: messy event tables, business questions in plain language, then SQL that answers them cleanly. You practice explaining the query out loud — the same way you would in a live case interview.</p><p>A practical drill: take one metric your team cares about (active users, GMV, ticket volume). Write the aggregation version, then rewrite it with windows so you keep grain and still answer “vs previous.” That before/after story is portfolio gold.</p><p>If you can defend when to use a window vs a join or a CTE, you are already past “I know SQL syntax” and into “I can think like an analyst.”</p>',
  'published',
  '2026-08-11T17:00:00.000Z'::timestamptz,
  'August 12, 2026',
  6,
  '6 min read'
),
(
  gen_random_uuid(),
  'from-messy-csv-to-stakeholder-ready-story',
  'Analytics',
  'From Messy CSV to a Stakeholder-Ready Story',
  'Cleaning is not the finish line. The win is a clear narrative: what changed, why it might have changed, and what to do next.',
  '<p>Real datasets arrive late, incomplete, and slightly wrong. Duplicate IDs, mixed date formats, nulls that mean three different things — that is normal. The analysts who get trusted are the ones who document assumptions while they clean.</p><p>Pandas (or BigQuery + notebooks) should get you to a trustworthy table. The second half of the job is framing: one insight, one chart that supports it, one recommendation. Stakeholders rarely want every pivot you tried.</p><p>Digica’s Mini Bootcamp Data Analytics runs this as a loop: load → clean → explore → visualize → present. Mentors push on “so what?” until your slide would survive a product standup.</p><p>Portfolio tip: show the before (raw quirks), the after (clean grain), and one decision your analysis would unlock. That beats a wall of colorful charts with no owner.</p><p>Outcome-focused learning means every lesson exists to ship that loop faster — not to collect more library names on a resume.</p>',
  'published',
  '2026-08-04T17:00:00.000Z'::timestamptz,
  'August 5, 2026',
  5,
  '5 min read'
),
(
  gen_random_uuid(),
  'why-your-first-ml-model-should-be-boring',
  'Data Science',
  'Why Your First ML Model Should Be Boring',
  'Start with a baseline you can explain. Complexity without a clear lift is how portfolios confuse interviewers.',
  '<p>Fancy architectures look great in demos. In interviews and on the job, the question is usually: Did you beat a simple baseline? Did you check leakage? Can a business person act on the prediction?</p><p>A “boring” first model — logistic regression or a shallow tree on well-engineered features — forces you to understand the problem. You learn which features matter, where labels are noisy, and what “good enough” means for the use case.</p><p>Digica’s Data Science Bootcamp sequences SQL and Python foundations before ML, then asks for a business capstone: not only accuracy, but implementation thinking — who consumes the score, how often it refreshes, what happens when it is wrong.</p><p>Document the baseline, the chosen model, the metric, and one failure mode. That write-up is often more persuasive than a black-box notebook with 0.01 AUC improvement.</p><p>Depth comes after clarity. Boring first models are how you earn the right to go deep.</p>',
  'published',
  '2026-07-27T17:00:00.000Z'::timestamptz,
  'July 28, 2026',
  7,
  '7 min read'
),
(
  gen_random_uuid(),
  'portfolio-projects-that-pass-the-hiring-manager-test',
  'Career',
  'Portfolio Projects That Pass the Hiring Manager Test',
  'Recruiters skim. Hiring managers dig. Build projects that survive both — with a problem, method, and business impact on the first screen.',
  '<p>A GitHub full of tutorial clones signals effort, not judgment. Hiring managers look for problem framing, tradeoffs, and whether you can talk about the work without reading the README.</p><p>Structure every project like a mini case: context → question → data → approach → result → limitation. Put that story above the code.</p><p>Digica cohorts ship portfolio-ready deliverables with mentor feedback for a reason: feedback is the difference between “I finished the notebook” and “I can defend this in a panel.”</p><p>Prefer one sharp project (SQL + viz, or EDA + simple model) over five half-finished repos. Depth beats volume when time is scarce.</p><p>If you are mid-transition, map each project to a role title you want (analyst vs scientist) so your narrative stays consistent across LinkedIn, CV, and interview.</p>',
  'published',
  '2026-07-19T17:00:00.000Z'::timestamptz,
  'July 20, 2026',
  5,
  '5 min read'
),
(
  gen_random_uuid(),
  'ctes-subqueries-and-readable-sql-teams-trust',
  'SQL',
  'CTEs, Subqueries, and SQL Teams Actually Trust',
  'Clever one-liners break in code review. Readable layered SQL survives handoffs — and that is a career skill.',
  '<p>Production analytics is collaborative. The next person to touch your query should not need a séance. CTEs let you name each step: filter events, aggregate daily, join dimensions, then select the final grain.</p><p>Subqueries are fine when the nest is shallow. When logic stacks, prefer CTEs so each block has a purpose you can test independently.</p><p>In Digica SQL sessions we grade clarity as hard as correctness: aliases, consistent grain, and comments only where intent is non-obvious.</p><p>Practice refactoring a nested mess into three CTEs. That exercise mirrors what you will do in your first week on a data team.</p><p>Trusted SQL is less about showing off and more about reducing surprise when the dashboard number moves.</p>',
  'published',
  '2026-07-13T17:00:00.000Z'::timestamptz,
  'July 14, 2026',
  6,
  '6 min read'
),
(
  gen_random_uuid(),
  'live-cohorts-vs-solo-video-what-actually-sticks',
  'Career',
  'Live Cohorts vs Solo Video: What Actually Sticks',
  'Recordings help you review. Live sessions force you to ship, ask, and get unstuck — the loop career changers need.',
  '<p>Self-paced libraries are generous with content and quiet on accountability. Many learners finish 40% and stall exactly when projects get ambiguous.</p><p>Live cohorts add deadlines, peers, and mentors who have shipped similar work. Ambiguity becomes a conversation instead of a closed tab.</p><p>Digica’s model — live sessions, recordings, project milestones — is designed so you can miss a night and still catch up, without losing the pressure to deliver.</p><p>Choose formats based on your bottleneck: if you lack structure, pick a cohort; if you only need a reference, video is enough. Most career movers need the first more than they admit.</p><p>Skills stick when you reuse them under light pressure: present a finding, answer a mentor challenge, revise once. That is the loop we optimize for.</p>',
  'published',
  '2026-07-06T17:00:00.000Z'::timestamptz,
  'July 7, 2026',
  4,
  '4 min read'
),
(
  gen_random_uuid(),
  'bigquery-habits-that-save-hours-every-week',
  'SQL',
  'BigQuery Habits That Save Hours Every Week',
  'Partition filters, dry runs, and naming conventions — small habits that keep costs down and queries reviewable.',
  '<p>Writing a query that returns the right answer is step one. Writing a query your team can rerun next month without a surprise bill is step two — and that is where BigQuery habits matter.</p><p>Start with partition and cluster awareness. Filter on the partition column early. Prefer SELECT of the columns you need. Use dry runs when exploring unfamiliar tables so you see bytes processed before you pay for a full scan.</p><p>In Digica SQL sessions we treat warehouse hygiene as part of the craft: aliases that match the grain, CTEs with clear names, and comments only where a future reader would otherwise guess wrong.</p><p>A useful drill: take one slow dashboard query and rewrite it with an earlier filter and fewer columns. Measure bytes processed before and after. That before/after note belongs in your portfolio as much as the chart.</p><p>Good SQL is not only correct — it is cheap enough to trust and clear enough to hand off.</p>',
  'published',
  '2026-06-29T17:00:00.000Z'::timestamptz,
  'June 30, 2026',
  6,
  '6 min read'
),
(
  gen_random_uuid(),
  'choosing-charts-that-answer-the-question',
  'Analytics',
  'Choosing Charts That Answer the Question',
  'Bar, line, or table? Pick the visual that matches the decision — not the one that looks busiest in a deck.',
  '<p>Pretty charts fail when stakeholders still ask “so what changed?” The right visual starts from the question: comparison, trend, composition, or distribution.</p><p>Comparisons favor bars. Trends favor lines with a clear time axis. Composition needs care — stacked bars and pies mislead when categories shift. Sometimes the best “chart” is a well-sorted table with one highlighted delta.</p><p>Digica Analytics projects grade storytelling as hard as Pandas: one insight, one supporting visual, one recommendation. Mentors cut decoration that does not move the decision.</p><p>Before you open a library, write the sentence you want the slide to prove. If the chart cannot carry that sentence, change the chart — not the font size.</p><p>Visualization is a communication skill. Treat it like SQL: intentional, testable, and easy to defend.</p>',
  'published',
  '2026-06-22T17:00:00.000Z'::timestamptz,
  'June 23, 2026',
  5,
  '5 min read'
),
(
  gen_random_uuid(),
  'feature-leakage-the-silent-portfolio-killer',
  'Data Science',
  'Feature Leakage: The Silent Portfolio Killer',
  'Impressive metrics that vanish in production usually share one cause — information from the future sneaking into training.',
  '<p>Leakage is when your model sees something it would not have at prediction time — a post-purchase flag, a target-derived score, or a join that quietly includes tomorrow’s labels.</p><p>Interviewers and hiring managers know the pattern: sky-high validation scores, vague feature lists, no discussion of when each column becomes available. Calling out leakage risk is a maturity signal.</p><p>In Digica’s Data Science Bootcamp, capstones are reviewed for train/serve consistency: which features exist at decision time, how you split by time, and what a failed prediction costs the business.</p><p>Practical check: for every feature, write one line — “available at prediction?” If you hesitate, drop it or rebuild it from only past data.</p><p>A slightly weaker honest model beats a perfect leaked one. Clarity about limitations is part of the deliverable.</p>',
  'published',
  '2026-06-15T17:00:00.000Z'::timestamptz,
  'June 16, 2026',
  7,
  '7 min read'
),
(
  gen_random_uuid(),
  'how-to-talk-about-your-project-in-interviews',
  'Career',
  'How to Talk About Your Project in Interviews',
  'A two-minute project story: context, approach, result, and limitation — practiced until it sounds natural under pressure.',
  '<p>Technical screens often start with “walk me through a project.” Candidates who ramble through tools lose the room. Candidates who lead with the business question keep attention.</p><p>Use a simple arc: context (who needed what), approach (data + method), result (metric or decision), limitation (what you would improve). Keep tools as supporting detail, not the headline.</p><p>Digica mentor feedback sessions rehearse this arc on purpose. Presenting to peers under light pressure is closer to an interview than polishing a README alone.</p><p>Record yourself once. Cut filler. Replace “I used Pandas” with “I cleaned duplicates and fixed date grain so weekly trends were trustworthy.”</p><p>Your project is not a museum of libraries — it is proof you can think with data and explain it.</p>',
  'published',
  '2026-06-08T17:00:00.000Z'::timestamptz,
  'June 9, 2026',
  5,
  '5 min read'
),
(
  gen_random_uuid(),
  'joins-that-match-the-business-grain',
  'SQL',
  'Joins That Match the Business Grain',
  'Fan-outs and double counts usually come from joining at the wrong grain — fix the grain first, then the join type.',
  '<p>INNER vs LEFT is not the hard part. Knowing whether you are joining orders to customers, or order lines to payments, is. Wrong grain creates silent fan-outs that inflate revenue until someone audits the dashboard.</p><p>Before you JOIN, write the primary key of each side and the grain of the output you need. If one side is many-to-many in disguise, aggregate first or use a bridge carefully.</p><p>Digica SQL projects use messy real-ish schemas on purpose: duplicate keys, late-arriving dimensions, and metrics that break if you skip the grain check.</p><p>Habit: after every join, spot-check row counts and a known total. If orders ballooned, you probably multiplied rows.</p><p>Analysts who protect grain earn trust. Syntax is easy to Google; judgment is what interviews try to surface.</p>',
  'published',
  '2026-06-01T17:00:00.000Z'::timestamptz,
  'June 2, 2026',
  6,
  '6 min read'
),
(
  gen_random_uuid(),
  'eda-checklist-before-you-model-anything',
  'Data Science',
  'An EDA Checklist Before You Model Anything',
  'Nulls, class balance, leakage risks, and a sanity baseline — the hour of EDA that saves a week of wrong modeling.',
  '<p>Jumping to fit a model feels productive. Skipping EDA is how you ship a model that predicts the label you accidentally left in the features.</p><p>A short checklist: target definition, missingness patterns, duplicates, class balance, time range, obvious outliers, and a dumb baseline (majority class or mean). Write what you found before you tune hyperparameters.</p><p>Digica’s path into ML assumes you can defend that checklist out loud. Mentors ask what surprised you in the data — not which library had the nicest API.</p><p>Keep a one-page EDA note in every repo. Future you (and interviewers) will thank you when metrics look “too good.”</p><p>Exploration is not procrastination when it prevents wasted modeling. Make it a gate, not a vibe.</p>',
  'published',
  '2026-05-25T17:00:00.000Z'::timestamptz,
  'May 26, 2026',
  6,
  '6 min read'
)
ON CONFLICT (slug) DO NOTHING;
